# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original_images/')),
                ('resized_image', models.ImageField(upload_to='resized_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resized_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
